#
# Mach Operating System
# Copyright (c) 1993,1992 Carnegie Mellon University
# All Rights Reserved.
# 
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
# 
# CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
# CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
# ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
# 
# Carnegie Mellon requests users of this software to return to
# 
#  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
#  School of Computer Science
#  Carnegie Mellon University
#  Pittsburgh PA 15213-3890
# 
# any improvements or extensions that they make and grant Carnegie Mellon
# the rights to redistribute these changes.
#
#
# HISTORY
# $Log:	Makefile,v $
# Revision 2.2  93/02/04  13:36:34  mrt
# 	Created to export include files that mig uses
# 
# Revision 2.2  93/02/04  13:36:26  mrt
# 	Created for ODE make
# 	[92/12/17            mrt]
# 
#
#	Export the machine dependent include files needed to 
#	build and run mig.
#

VPATH		= ../../../../mach/mips

INCLUDES	= boolean.h kern_return.h vm_types.h \
		  machine_types.defs

EXPDIR		= /include/mach/mips/

.include <${RULES_MK}>
